# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Toiling in the bit fields
description: >
  This is an experiment in getting things out of my head and recorded somewhere.
  Thoughts are mine and mine alone (unless otherwise noted). I plan on mostly writing about
  being CTO of a growing company, with some programming miscellenia thrown in for good
  measure.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nick.demonner.net" # the base hostname & protocol for your site
twitter_username: ndemonner
github_username:  ndemonner

# Build settings
markdown: kramdown
